package quest.kana.backend.support.error;

public interface ErrorCodes {
    String E_UNSUPPORTED_AUTHENTICATION_TYPE = "E_UNSUPPORTED_AUTHENTICATION_TYPE";
    String E_EMPTY_USERNAME = "E_EMPTY_USERNAME";
    String E_EMPTY_PASSWORD = "E_EMPTY_PASSWORD";
    String E_UNKNOWN_USERNAME = "E_UNKNOWN_USERNAME";
    String E_ACCOUNT_LOCKED = "E_ACCOUNT_LOCKED";
    String E_BAD_CREDENTIALS = "E_BAD_CREDENTIALS";
    String E_ACCOUNT_DISABLED = "E_ACCOUNT_DISABLED";
}
